/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_mpi_media_FFAudioExtractor */

#ifndef _Included_nl_mpi_media_FFAudioExtractor
#define _Included_nl_mpi_media_FFAudioExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    setDebugMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_media_FFAudioExtractor_setDebugMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    isDebugMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nl_mpi_media_FFAudioExtractor_isDebugMode
  (JNIEnv *, jclass);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    initLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_media_FFAudioExtractor_initLog
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    initNativeFF
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_media_FFAudioExtractor_initNativeFF
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getSampleFrequencyFF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_media_FFAudioExtractor_getSampleFrequencyFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getBitsPerSampleFF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_media_FFAudioExtractor_getBitsPerSampleFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getNumberOfChannelsFF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_media_FFAudioExtractor_getNumberOfChannelsFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getFormatTagFF
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_media_FFAudioExtractor_getFormatTagFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getDurationMsFF
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_media_FFAudioExtractor_getDurationMsFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getDurationSecFF
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_nl_mpi_media_FFAudioExtractor_getDurationSecFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getSampleBufferSizeFF
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_media_FFAudioExtractor_getSampleBufferSizeFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getSampleBufferDurationMsFF
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_media_FFAudioExtractor_getSampleBufferDurationMsFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getSampleBufferDurationSecFF
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_nl_mpi_media_FFAudioExtractor_getSampleBufferDurationSecFF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getSamplesFF
 * Signature: (JDDLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_media_FFAudioExtractor_getSamplesFF
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jobject);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    getSampleFF
 * Signature: (JDLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_media_FFAudioExtractor_getSampleFF
  (JNIEnv *, jobject, jlong, jdouble, jobject);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    setPositionSecFF
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_mpi_media_FFAudioExtractor_setPositionSecFF
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     nl_mpi_media_FFAudioExtractor
 * Method:    releaseFF
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_media_FFAudioExtractor_releaseFF
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
